import { Geist, Geist_Mono } from "next/font/google";

import "./cutom.css";
import "./globals.css";
import Footer from "./components/Footer";
import SmoothScroll from "./components/SmoothScroll";
import EnquiryModalProvider from "./components/EnquiryModalProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Mother mira",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html
        lang="en"
        className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      >
        <body className="min-h-full flex flex-col">
          <EnquiryModalProvider>
            <SmoothScroll>
              <main className="flex-1">{children}</main>
              <Footer />
            </SmoothScroll>
          </EnquiryModalProvider>
        </body>
      </html>
    </>
  );
}
